<p>À partir de ce moment-là, je m’intéressais sans réserve à cette cuisine autochtone. Je me mis à accompagner mon hôte dans ses activités d’« agronome ». C’est à cette occasion que je découvris l’écosystème du dôme, même si au début j’en profitais surtout pour étudier à la dérobée ce fabuleux soleil qui pourrait peut-être sauver mon peuple.</p>
<p>L’attitude d’Ed Gaïa à l’égard de ses cultures était une source constante d’étonnement : avec quelle délicatesse il touchait les plantes ! Comme si leur valeur était aussi inestimable que celle de l’uranium.</p>
<p>« Tu vois, me répétait-il sans cesse, les plats que tu dégustes chaque jour à ma table ne seraient rien sans les aliments qui les composent. Le meilleur cuisinier du monde ne réaliserait qu’un plat fade sans des produits de qualité. C’est pourquoi tu dois toujours les choisir avec soin. » Or en la matière, rien ne valait la pratique pour Ed Gaïa.</p>
<p>— Regarde ces chiwongas, me dit-il tandis qu’il en cueillait deux sur un arbuste à proximité. Selon toi, lequel devrais-je choisir pour le repas de ce soir ?</p>
<p>— Mais ils sont identiques ! Ils ont la même couleur, la même forme. Je suis sûr qu’ils ont tous les deux le même goût.</p>
<p>— Détrompe-toi. Ne te fie pas à leur apparence. Il faut sentir leur arôme, les tâter. Trop dur, il n’est pas assez mûr. Trop mou, c’est qu’il va bientôt se gâter.</p>
<p>J’étais très sceptique. Mon entraînement de soldat m’avait habitué à repérer du premier coup d’œil les détails discordants.  Néanmoins, je savais qu’il ne fallait jamais estimer un ennemi d’après son allure.</p>
<p>— Celui dans ma main droite est assez résistant sous mes doigts. Mais l’autre par comparaison me semble très malléable, comme prêt à éclater sous la pression. Je choisirais donc le premier.</p>
<p>— Ton raisonnement serait bon avec d’autres produits, mais un chiwonga mûr est par nature plus souple que ferme. Vois-tu, chaque fruit a ses propres caractéristiques, m’expliqua Ed Gaïa. C’est pourquoi tu dois tous les connaître si tu veux les choisir au mieux. A présent, sens les chiwongas et tu comprendras ton erreur.</p>
<p>Je les rapprochai successivement de mon nez. Le premier embaumait un léger parfum rafraîchissant. Au tour du second, la senteur se fit nettement plus intense et précise, me révélant ma méprise.</p>
<p>Pour parfaire l’exercice et me « former le palais », Ed Gaïa me les fit goûter. Si je savourais le premier, ce ne fut rien en comparaison du second. Son goût nettement plus prononcé et sa consistance plus douce furent un délice pour mes papilles.</p>
<p>Un constat s’imposa alors à mon esprit : la nourriture brute peut avoir du goût ! Après mon premier repas local, j’avais supposé que c’était la préparation qui donnait toute sa saveur à l’aliment. En l’absence de ce savoir, mon peuple ne pouvait réaliser de telles prouesses culinaires. Mais voici que j’étais mis nez à nez avec mon erreur. Il fallait que j’en sache plus :</p>
<p>— Ed Gaïa, dis-moi, est-ce votre soleil qui donne une telle saveur aux légumes ?</p>
<p>— Bien sûr que non ! Enfin, pas directement. C’est la nature qui crée les fruits et les légumes goûtus. Notre technologie ne sert qu’à recréer l’écosystème d’avant la tragédie du volcan pour que la nature puisse continuer comme auparavant à nous offrir ses produits.</p>
<p>Quel choc ! Cela bouleversait ma conception du monde ! Et si la véritable clé de la survie n’était pas d’utiliser nos technologies pour nous adapter mais pour protéger notre environnement ? Et si ce mode de vie nous permettait de retrouver la douceur de vivre tant vantée par les vieilles légendes ?</p>
<p>Dans tous les cas, cette découverte attisa ma curiosité comme jamais. Chaque jour, Ed Gaïa me faisait découvrir des goûts que je ne connaissais pas. Mais je voulais en savoir plus.</p>
		