<div align="center">*</div>
  
<p>Lorsque j'ouvris les yeux à nouveau, mon corps endolori m'empêchait de me mouvoir à ma guise.<br />
Si je n'étais plus prisonnier de cette cloche de sève, j'étais désormais captif de ma propre carcasse de muscles et de métaux. De la couche si confortable sur laquelle j'étais allongé, j'observais la pièce dans laquelle je me trouvais. Les murs étaient d'un blanc immaculé, c'était inédit pour moi qui n'avait connu que cendres. Une lumière si vive inondait ce lieu étonnant grâce à une baie vitrée démesurée. Dehors se mêlaient paysages ruraux et urbains dans une surprenante harmonie. Soudain, on frappa à la porte. Un homme passa son visage par l'entrebâillement de celle-ci. Son corps était dépourvu de tout organe mécanique et sa peau légèrement bronzée était comme nourrie par le soleil artificiel qui arrosait de lumière ce lieu inédit. Je rencontrai pour la première fois celui que je pensais encore être mon geôlier, Ed Gaïa. </p>
  
<div align="center">*</div>
  
<p>Mes membres, broyés par la pression de la sève, me faisaient encore souffrir. Nul besoin d'être médecin pour comprendre que ma convalescence en territoire ennemi s'annonçait effroyablement longue. Malgré ma détermination pour l'écourter au maximum, j'étais loin de m'imaginer à quel point une chose aussi simple que de manger pour reprendre des forces allait être aussi difficile.<br />
  La dernière gélule que j'avais absorbée couvrait encore mes besoins, mais rapidement la faim se fit sentir. Mon hôte me proposa alors ce qu'il appelait un « petit déjeuner ». Des « aliments », choses comestibles aux formes, couleurs et textures totalement inconnues trônaient sur la table. Dans un récipient se trouvait une sorte de liquide de couleur marron et d'une étrange onctuosité. Plus loin, une denrée vaguement ovale d'un vert tendre, à la texture grumeleuse, qu'ils nommaient « papaye ». Encore après, une boule à la surface craquelée, comme dans les légendes sur ces produits oubliés depuis l'éruption du grand volcan.<br />
  Ils exhalaient tous un parfum délicat. Ce n'était pas désagréable, non… même plutôt l'inverse. Mais depuis quand la nourriture a une odeur ? Passé l'étonnement, mon instinct de soldat revint en force : et si c'était du poison ? Des substances étranges, offertes de la main d'un ennemi qui soigne celui qui l'a attaqué la veille…  <br />
  Ed Gaïa sembla lire dans mon esprit. Il sépara la boule en deux. La surface se rompit, révélant alors à l'intérieur une texture moelleuse à souhait. Cette action embauma la pièce d'un effluve doux et sucré, qui me mit l'eau à la bouche. Sur le coup, je ne compris pas bien pourquoi mon corps réagissait ainsi. Depuis quand l'organisme s'émeut face à de la nourriture ? Ce n'est que bien plus tard que j'appris qu'il s'agissait d'une réaction normale lorsqu'un aliment nous fait envie.<br />
  Toutes ces nouvelles sensations alimentèrent ma méfiance. Ed Gaïa commença alors à manger l'un des deux morceaux, pour me prouver que c'était sans danger. Je restai de glace. Il n'insista pas, semblant comprendre mes réticences.</p>
  
<div align="center">*</div>
  
<p>Pendant qu'Ed Gaïa vaquait à ses occupations, je restais souvent seul chez lui. En bon soldat, j'en profitais pour étudier l'environnement, malgré mon état de faiblesse lié à ma blessure et à mon jeûne. <br />
  Un jour, je tombai sur un holographe qui à mon contact projeta sur les murs des images de ces mets indigènes, accompagnées de commentaires. L'hologramme était intitulé Recettes d'antan. Les illustrations attiraient irrémédiablement mon regard avec toutes ces couleurs, du bleu profond au jaune pétillant. Et qu'est-ce que les aliments avaient l'air appétissant ! Je me mis à lire le texte.<br />
  Apparemment, il décrivait une marche à suivre, sûrement pour préparer le produit sur l'image d'à côté. Mais quel langage obscur ! Je n'en comprenais pas la moitié. Cependant, sous l'emprise irrésistible de ma curiosité, je continuais à parcourir l'hologramme jour après jour.</p>

<div align="center">*</div>
  
<p>Un matin, poussé par la famine et l'appétit aiguisé par ma découverte de la veille, je me décidai finalement à expérimenter la nourriture de mon hôte. Un sourire discret naquit sur les lèvres d'Ed Gaïa quand je lui demandai à manger.<br />
  Je jetai mon dévolu sur la fameuse boule qui m'avait fait saliver quelques jours auparavant. Je tâtai d'abord prudemment. L'extérieur était légèrement solide, rugueux au toucher. C'était tellement différent de ma gélule toute lisse et uniforme ! Mais dès que j'appuyais plus fort, mon doigt s'enfonçait en plein cœur de l'aliment, à la fois moelleux et ferme. L'arôme dégagé me mit une fois de plus l'eau à la bouche. Ne tenant plus, je détachai un morceau et le goûtai.<br />
  Ce fut une explosion de saveurs pour mon palais. À la place du goût insipide habituel, celui qui s'épanouit sur ma langue était légèrement fruité. Mais, tandis que la surface craquelée disparaissait pour mettre à nu le cœur moelleux et fondant, la saveur laissa place à une impression intense de douceur et de chaleur, tel un feu qui réchauffe les membres transis par le froid de l'hiver. Aussi fugace qu'avait été cette expérience, j'en restais abasourdi. Moi pour qui manger se résumait à un acte de survie, ma conception du repas en fut totalement chamboulée.</p>
