<p>« Adieu mon ami, adieu dôme salutaire… »</p>

<p>Voilà cinq cents ans que le grand volcan entra en éruption. Le magma s'en échappant recouvrit des terres, jusqu'alors fertiles, sur des milliers de kilomètres. Des blocs de lave solidifiés semblables à des maisons se déversèrent sur les métropoles tels des pluies d'astéroïdes et le ciel disparut à jamais sous l'épaisse nuée ardente. Face à cette catastrophe destructrice, l'humanité, réduite à une poignée d'individus, dut faire un choix : se protéger ou s'adapter.</p>

<p>À ma naissance, on m'implanta des poumons bioniques capables de filtrer le nuage pyroclastique, on m'injecta des produits modifiant ma peau d'enfant en épaisse cuirasse résistante. Chacun de mes organes devint une arme contre l'hostilité d'un monde dévasté. Mon nom est Raynor Hell, et ma vie consiste à rendre le quotidien de mes pairs plus confortable.</p>

<p>Mon peuple a subsisté en colonie au sein de laquelle chacun de nous joue un rôle crucial. Des médecins rectifient les nouveau-nés pour leur permettre de survivre. Les ouvriers extraient les minerais d'uranium, première source d'énergie de nos organes mécaniques. Des scientifiques clonent des matières organiques naturelles qu'ils transforment en gélules pour nourrir nos muscles et notre sang. Moi, je suis militaire et explorateur, je suis entraîné pour rechercher de nouveaux gisements d'uranium à travers le globe. La tâche est rude...</p>
<p>Durant un demi-millénaire nous avons rongé le sol pour en extraire ce précieux « gâteau jaune », mais aujourd'hui les filons se font rares et mon peuple voit en cette pénurie son extinction inéluctable.</p>

<p>Un jour, à la tête de mon unité, je parcourais les landes dévastées où ni l'éclat du soleil, ni la beauté de la vie ne sauraient prendre part. Nous avancions à tâtons, à la lueur de nos phares, lorsque nos véhicules amphibies rencontrèrent l'océan. Nous fîmes une halte sur une plage de galets noirs pour avaler une gélule concentrée en protéines et une recharge de plutonium. La première pour rassasier nos corps naturels durant trois jours et la seconde pour alimenter nos organes bioniques. C'est là que je le vis pour la première fois.</p>

<p>Au large, une lueur intense semblait percer l'épaisse masse de poussière volatile. Nous reprenions les véhicules pour percevoir plus précisément cette source de lumière. Après une paire de kilomètres, nous tombions nez à nez avec un édifice gigantesque. Un dôme si colossal que nous n'en vîmes pas le sommet. De celui-ci s'échappait une lumière semblable à celle du soleil. De mémoire d'explorateur, jamais nous n'avions trouvé signe de vie sur les continents que nous avions visités. Nous mîmes des jours entiers à en faire le tour, sans trouver un seul accès nous permettant de rentrer à l'intérieur de ce formidable écrin. De l’extérieur, nous distinguions de vastes espaces de verdures, des étendues d'eau si claire et des espèces vivantes dont j'ignorais encore le nom.</p>
<p>Je pris la décision de rentrer à la colonie avec mon unité et colporter la découverte de cet élysée auprès de mon peuple.</p>
<p>De retour dans nos contrées sordides, je rédigeais un rapport d'exploration. J'y décrivais les champs de blé et de tournesol, les forêts centenaires, les chevaux au galop dans les prairies, ce soleil irréel et ce dôme infrangible sous lequel la vie avait germé. La nouvelle eut un fort retentissement. Mon peuple vit en ce dôme la source d'énergie indispensable à sa survie, l'alternative à l'uranium dont les ressources manquaient cruellement. Le lendemain je reçus l'ordre de réunir mon unité armée pour créer une brèche à la surface de ce dôme, nous y introduire et mettre la main sur ce soleil fabuleux. Nous partîmes le soir même avec la ferme conviction de revenir en héros.</p>