<p>Le lendemain de notre repas, j’allais le voir. Il était dans sa chambre et n’avait pas l’air d’être déjà levé. Lorsque j’entrai, il était dans son lit, il soupira lourdement puis se mît à marmotter quelque chose d’incompréhensible. De cette frénésie, je compris seulement qu’il souffrait d’une intense douleur au ventre tétanisant tout son corps. Effrayé de le voir en pareil état, je pensais à tout ce qu’on avait fait ensemble durant ces jours et surtout à notre dernier repas. Je cherchais mes mots quand Ed Gaïa susurra :<br/>
— C’est seulement maintenant que je me rends compte de la bêtise qu’on a fait. Ce repas…<br/>
Il n’eut pas le temps de finir sa phrase que ses yeux étaient déjà fermés. Il se tut et plus aucun mot ne semblait pouvoir sortir de sa bouche. J’essayais de l’aider, de lui parler, d’écouter son cœur mais tout était vain. Son corps était mou et il ne bougea plus. Plus du tout.<br/>En comprenant que je ne pouvais pas faire plus moi-même, je partis chercher quelqu’un capable de le sauver. J’alertai deux de ses voisins qui apparemment étaient ses amis.<br/>
Ils accoururent auprès d’Ed Gaïa mais il restait immobile. Je voulus leur demander s’ils savaient comment forcer ce corps insensible à reprendre conscience quand tout à coup, ils me crièrent dessus. Ils m’accusèrent d’avoir tué Ed Gaïa. Pourtant, comment aurais-je pu le tuer après tout ce qu’il m’avait apporté ?<br/>
— Attendez ! Écoutez-moi !<br/>
Mais ils refusèrent et me jetèrent dans la rue où la foule s’amassait, alarmée par les cris.<br/>
J’aurais voulu me justifier, leur dire toute la vérité, mais ils insistèrent pour me voir partir sans tarder. Complètement désespéré, je n’eus plus la force de leur faire face et m’enfuis…</p>
<p>Cher Ed ! Ed Gaïa !<br/>
Dans ma tête ne sonnait que sa dernière phrase : « C’est seulement maintenant que je me rends compte de la bêtise qu’on a fait. Ce repas… ». Je pensai à ce dernier repas, à Ed Gaïa qui avait l’air tellement enchanté. Malgré ses remarques sur le goût du plat, il m’avait félicité d’avoir su tout réaliser par moi-même et de lui avoir fait découvrir un ingrédient de chez moi. Cependant, j’avais omis une seule chose : notre différence. Mon corps était modifié génétiquement et adapté pour résister à toute sorte de nourriture qui aurait pu être potentiellement dangereuse pour un humain comme lui. À cet instant-là je voulus mourir rien que pour échanger ma vie contre la sienne. Hélas ! Ce n’était pas possible, il nous avait quittés à jamais...</p>
<p>Dès lors, rejeté par mon peuple et par le dôme, j’errais loin de ces deux civilisations. Je me retrouvais là où il n’y avait plus rien sauf la terre fendillée, craquant sous mes pieds.</p>
<p>« Adieu mon ami, adieu dôme salutaire… »</p>